---
namespace: trippsc2
name: general
version: 2.3.5
readme: README.md
authors:
  - Jim Tarpley
description: This collection contains general purpose Ansible plugins.

license_file: 'LICENSE'

tags: []

dependencies:
  ansible.windows: '>=1.0.0'
  community.crypto: '>=1.0.0'

repository: https://github.com/trippsc2/ansible-collection-general.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json <namespace>-<name>-*.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
