---
namespace: trippsc2
name: general
version: '2.3.1'
readme: README.md
authors:
  - Jim Tarpley
description: This collection contains general purpose Ansible plugins.

license_file: 'LICENSE'

tags: []

dependencies:
  ansible.windows: '>=1.0.0'
  community.crypto: '>=1.0.0'

repository: https://github.com/trippsc2/ansible-collection-general.git

build_ignore:
  - .gitignore
