---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky9_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: self_signed_certificate_linux_pipe_
    groups:
      - subjects
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        _cert_certificate_path: >-
          {{ '/etc/pki/tls/certs/cert.crt' if ansible_os_family == 'RedHat' else '/etc/ssl/certs/cert.crt' }}
        _cert_private_key_path: >-
          {{ '/etc/pki/tls/private/cert.key' if ansible_os_family == 'RedHat' else '/etc/ssl/private/cert.key' }}
        cert_private_key_to_file: false
        cert_private_key_to_variable: true
        cert_certificate_to_file: false
        cert_certificate_to_variable: true
        cert_existing_certificate_type: pipe
        cert_private_key_passphrase: SecurePassphrase123!
verifier:
  name: ansible
