---
- name: Converge
  hosts:
    - subjects
  pre_tasks:
    - name: Set existing certificate content
      when:
        - generate_existing_cert
      block:
        - name: Get existing certificate content 
          become: true
          ansible.builtin.slurp:
            src: "{{ _cert_certificate_path }}"
          register: _cert_existing

        - name: Set existing certificate content variable
          ansible.builtin.set_fact:
            cert_existing_certificate_content: "{{ _cert_existing.content | b64decode }}"

  roles:
    - trippsc2.general.generate_csr
  tasks:
    - name: Copy private key content to file
      when:
        - cert_private_key_content | default('') != ''
      become: true
      ansible.builtin.copy:
        content: "{{ cert_private_key_content }}"
        dest: "{{ _cert_private_key_path }}"
        owner: test
        group: test
        mode: '0600'

    - name: Copy CSR content to file
      when:
        - cert_csr_content | default('') != ''
      become: true
      ansible.builtin.copy:
        content: "{{ cert_csr_content }}"
        dest: /tmp/cert.csr
        owner: vagrant
        group: vagrant
        mode: '0644'
