---
- name: Verify
  hosts:
    - subjects
  become: true
  tasks:
    - name: Get private key file info
      ansible.builtin.stat:
        path: "{{ _cert_private_key_path }}"
      register: _private_key_info

    - name: Get CSR file info
      ansible.builtin.stat:
        path: /tmp/cert.csr
      register: _csr_info

    - name: Verify private key exists
      ansible.builtin.assert:
        that:
          - _private_key_info.stat.exists
        fail_msg: Private key file does not exist.
        success_msg: Private key file exists.

    - name: Verify private key owner
      ansible.builtin.assert:
        that:
          - _private_key_info.stat.pw_name == 'test'
        fail_msg: Private key file does not have expected owner.
        success_msg: Private key file has expected owner.

    - name: Verify private key group
      ansible.builtin.assert:
        that:
          - _private_key_info.stat.gr_name == 'test'
        fail_msg: Private key file does not have expected group.
        success_msg: Private key file has expected group.

    - name: Verify private key mode
      ansible.builtin.assert:
        that:
          - _private_key_info.stat.mode == '0600'
        fail_msg: Private key file does not have expected mode.
        success_msg: Private key file has expected mode.

    - name: Verify that CSR file exists
      when:
        - expected_csr
      ansible.builtin.assert:
        that:
          - _csr_info.stat.exists
        fail_msg: CSR file does not exist.
        success_msg: CSR file exists.

    - name: Verify that CSR file does not exist
      when:
        - not expected_csr
      ansible.builtin.assert:
        that:
          - not _csr_info.stat.exists
        fail_msg: CSR file exists.
        success_msg: CSR file does not exist.
