---
- name: Verify
  hosts:
    - subjects
  tasks:
    - name: Set file path variables | Debian-based
      when:
        - ansible_os_family == 'Debian'
      ansible.builtin.set_fact:
        _private_key_path: /etc/ssl/private/cert.key
        _certificate_path: /etc/ssl/certs/cert.crt

    - name: Set file path variables | RedHat-based
      when:
        - ansible_os_family == 'RedHat'
      ansible.builtin.set_fact:
        _private_key_path: /etc/pki/tls/private/cert.key
        _certificate_path: /etc/pki/tls/certs/cert.crt

    - name: Set expected variables
      ansible.builtin.set_fact:
        private_key_owner: "{{ cert_private_key_owner | default('root') }}"
        private_key_group: "{{ cert_private_key_group | default('root') }}"
        private_key_mode: "{{ cert_private_key_mode | default('0600') }}"
        certificate_owner: "{{ cert_certificate_owner | default('root') }}"
        certificate_group: "{{ cert_certificate_group | default('root') }}"
        certificate_mode: "{{ cert_certificate_mode | default('0644') }}"

    - name: Get private key file info
      become: true
      ansible.builtin.stat:
        path: "{{ cert_private_key_path | default(_private_key_path) }}"
      register: _private_key_info

    - name: Get certificate file info
      become: true
      ansible.builtin.stat:
        path: "{{ cert_certificate_path | default(_certificate_path) }}"
      register: _certificate_info

    - name: Get CSR file info
      become: true
      ansible.builtin.stat:
        path: "{{ cert_csr_tmp_path | default('/tmp/cert.csr') }}"
      register: csr_info

    - name: Assert that private key info is expected
      ansible.builtin.assert:
        that:
          - _private_key_info.stat.pw_name == private_key_owner
          - _private_key_info.stat.gr_name == private_key_group
          - _private_key_info.stat.mode == private_key_mode
        fail_msg: Private key info is not as expected
        success_msg: Private key info is as expected

    - name: Assert that certificate info is expected
      ansible.builtin.assert:
        that:
          - _certificate_info.stat.pw_name == certificate_owner
          - _certificate_info.stat.gr_name == certificate_group
          - _certificate_info.stat.mode == certificate_mode
        fail_msg: Certificate info is not as expected
        success_msg: Certificate info is as expected

    - name: Assert that CSR does not exist
      ansible.builtin.assert:
        that:
          - not csr_info.stat.exists
        fail_msg: CSR was not deleted
        success_msg: CSR was deleted
