---
- name: Create Google Cloud DNS record
  delegate_to: localhost
  google.cloud.gcp_dns_resource_record_set:
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file | default(omit) }}"
    service_account_contents: "{{ gcp_service_account_contents | default(omit) }}"
    access_token: "{{ gcp_access_token | default(omit) }}"
    project: "{{ gcp_project }}"
    scopes: "{{ gcp_scopes | default(omit) }}"
    managed_zone:
      dnsName: "{{ gcp_dns_managed_zone_dns_name }}"
      name: "{{ gcp_dns_managed_zone_name }}"
    name: "{{ gcp_dns_record_name }}"
    type: "{{ gcp_dns_record_type }}"
    ttl: "{{ gcp_dns_record_ttl | default(omit) }}"
    target: "{{ gcp_dns_record_target }}"
    state: present
