---
- name: Gather OS facts
  when:
    - ansible_os_family is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution
      - os_family

- name: Validate OS Family is supported
  ansible.builtin.assert:
    that:
      - ansible_os_family in _cert_supported_os_families
    fail_msg: "OS Family '{{ ansible_os_family }}' is not supported."
    success_msg: "OS Family '{{ ansible_os_family }}' is supported."

- name: Include OS family variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Get OS user data
  when:
    - ansible_os_family != 'Windows'
  ansible.builtin.getent:
    database: passwd
    split: ':'

- name: Get OS group data
  when:
    - ansible_os_family != 'Windows'
  ansible.builtin.getent:
    database: group
    split: ':'

- name: Validate private key owner user exists
  when:
    - ansible_os_family != 'Windows'
  ansible.builtin.assert:
    that:
      - cert_private_key_owner in getent_passwd.keys()
    fail_msg: "User '{{ cert_private_key_owner }}' does not exist."
    success_msg: "User '{{ cert_private_key_owner }}' exists."

- name: Validate private key group exists
  when:
    - ansible_os_family != 'Windows'
  ansible.builtin.assert:
    that:
      - cert_private_key_group in getent_group.keys()
    fail_msg: "Group '{{ cert_private_key_group }}' does not exist."
    success_msg: "Group '{{ cert_private_key_group }}' exists."

- name: Validate RSA private key size
  when:
    - cert_private_key_type == 'RSA'
  ansible.builtin.assert:
    that:
      - cert_private_key_size | int > 512
    fail_msg: RSA private key size must be greater than 512.
    success_msg: RSA private key size is valid.

- name: Validate DSA private key size
  when:
    - cert_private_key_type == 'DSA'
  ansible.builtin.assert:
    that:
      - cert_private_key_size | int in _cert_allowed_dsa_key_sizes
    fail_msg: "DSA private key size is not valid. Valid sizes are: {{ _cert_allowed_dsa_key_sizes | join(', ') }}"
    success_msg: DSA private key size is valid.

- name: Validate Subject Alternative Name
  loop: "{{ cert_subject_alternative_names }}"
  ansible.builtin.assert:
    that:
      - item | regex_search('^(dirName|DNS|email|IP|RID|otherName|URI):')
    fail_msg: "Subject Alternative Name '{{ item }}' is not valid."
    success_msg: "Subject Alternative Name '{{ item }}' is valid."
