---
- name: Prepare Vault
  hosts:
    - subjects
  roles:
    - role: trippsc2.hashi_vault.testing
  tasks:
    - name: Create users
      loop:
        - vaultuser1
        - vaultuser2
        - vaultuser3
        - vaultuser4
        - testuser1
        - testuser2
        - testuser3
      become: true
      ansible.builtin.user:
        name: "{{ item }}"
        password: "{{ 'DefaultPassword123!' | password_hash('sha512') }}"
        state: present
        update_password: on_create

    - name: Add users to wheel group to allow SSH (EL 8)
      loop:
        - vaultuser1
        - vaultuser2
        - vaultuser3
        - vaultuser4
        - testuser1
        - testuser2
        - testuser3
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '8'
      become: true
      ansible.builtin.user:
        name: "{{ item }}"
        groups:
          - wheel
        append: true

    - name: Create HashiCorp Vault mount point
      delegate_to: localhost
      trippsc2.hashi_vault.vault_kv2_secret_engine:
        token: "{{ vault_token }}"
        url: "{{ vault_url }}"
        engine_mount_point: "{{ rotate_vault_mount_point }}"
        state: present

    - name: Create HashiCorp Vault secret
      loop:
        - vaultuser2
        - vaultuser3
        - vaultuser4
      delegate_to: localhost
      community.hashi_vault.vault_kv2_write:
        token: "{{ vault_token }}"
        url: "{{ vault_url }}"
        engine_mount_point: "{{ rotate_vault_mount_point }}"
        path: "{{ inventory_hostname }}/users/{{ item }}"
        data:
          password: DefaultPassword123!
