---
- name: Verify
  hosts:
    - all
  gather_facts: false
  tasks:
    - name: Get content of winca.pem
      ansible.builtin.slurp:
        src: /home/vagrant/winca.pem
      register: _winca_content

    - name: Get content of dc.pem
      ansible.builtin.slurp:
        src: /home/vagrant/dc.pem
      register: _dc_content

    - name: Combine certificates
      ansible.builtin.set_fact:
        _combined_cert: "{{ _winca_content.content | b64decode }}\n{{ _dc_content.content | b64decode }}"

    - name: Get content of combined.pem
      ansible.builtin.slurp:
        src: /home/vagrant/combined.pem
      register: _combined_content

    - name: Assert combined.pem is equal to winca.pem + dc.pem
      ansible.builtin.assert:
        that:
          - _combined_cert == _combined_content.content | b64decode
        fail_msg: Combined certificate does not have the same content as winca.pem + dc.pem.
        success_msg: Combined certificate has the same content as winca.pem + dc.pem.
