---
argument_specs:
  main:
    short_description: ACME Certificate - DNS Challenge
    description:
      - This role generates an ACME TLS certificate.
      - The role depends on the `trippsc2.general.generate_csr` role to generate a private key and CSR.
      - The role depends on another role to set a DNS TXT record for the ACME challenge.
      - |
        The role does the following:
          - Runs the `trippsc2.general.generate_csr` role to generate a private key and CSR, if needed.
          - If the private key and CSR are generated, the role issues a dns-01 challenge to the ACME server.
          - The DNS role is responsible for setting the DNS TXT record for the ACME challenge.
          - Once the DNS record is set, the role will request the certificate from the ACME server and store it in the `cert_certificate_content` variable.
          - Optionally, the role will save the certificate to a file.
    author:
      - Jim Tarpley (@trippsc2)
    options:
      cert_acme_account_key_content:
        type: str
        required: true
        no_log: true
        description:
          - The contents of the account key.
          - This is used to identify yourself to the ACME server when revoking the certificate, as opposed to the private key of the certificate.
      cert_acme_account_key_passphrase:
        type: str
        required: false
        no_log: true
        description:
          - The passphrase for the account key.
          - If not provided, the account key is assumed to be unencrypted.
      cert_acme_account_email:
        type: str
        required: true
        description:
          - The email address to use for the ACME account.
      cert_acme_account_uri:
        type: str
        required: false
        description:
          - The URI of the ACME account.
          - This is used to revoke the certificate.
      cert_acme_directory:
        type: str
        required: true
        description:
          - The ACME directory URL.
      cert_acme_version:
        type: int
        required: false
        default: 2
        choices:
          - 1
          - 2
        description:
          - The ACME version to use.
      cert_acme_terms_agreed:
        type: bool
        required: false
        description:
          - Whether the terms of service should be agreed to.
      cert_acme_intermediate_certificate_to_file:
        type: bool
        required: false
        default: true
        description:
          - Whether to save the intermediate certificate to a file.
      cert_acme_intermediate_certificate_to_variable:
        type: bool
        required: false
        default: false
        description:
          - Whether to store the intermediate certificate in a variable.
          - If set to `true`, the intermediate certificate will be stored in the `cert_acme_intermediate_certificate_content` variable.
      cert_acme_intermediate_certificate_path:
        type: path
        required: false
        description:
          - The path to save the intermediate certificate file.
          - If *cert_acme_intermediate_certificate_to_file* is `true`, this is required.
      cert_acme_intermediate_certificate_owner:
        type: str
        required: false
        default: root
        description:
          - The owner of the certificate on Linux systems.
          - On Windows systems, this is ignored.
      cert_acme_intermediate_certificate_group:
        type: str
        required: false
        default: root
        description:
          - The group of the certificate on Linux systems.
          - On Windows systems, this is ignored.
      cert_acme_intermediate_certificate_mode:
        type: str
        required: false
        default: '0644'
        description:
          - The mode of the certificate on Linux systems.
          - On Windows systems, this is ignored.
      cert_acme_validate_certs:
        type: bool
        required: false
        default: true
        description:
          - Whether to validate the ACME server certificates.
      cert_acme_dns_role:
        type: str
        required: true
        choices:
          - trippsc2.general.gcp_dns_record
          - custom
        description:
          - The role to use to set the DNS TXT record for the ACME challenge.
          - If set to `custom`, the `cert_acme_custom_dns_role` variable must be defined.
      cert_acme_custom_dns_role:
        type: str
        required: false
        description:
          - The custom role to use to set the DNS TXT record for the ACME challenge.
          - This is required if *cert_acme_dns_role* is set to `custom`.
      cert_certificate_to_file:
        type: bool
        required: false
        default: true
        description:
          - Whether to generate the certificate to a file.
          - If set to `true`, the certificate will be stored at the path specified in the `cert_certificate_path` variable.
      cert_certificate_to_variable:
        type: bool
        required: false
        default: false
        description:
          - Whether to store the certificate in a variable.
          - If set to `true`, the certificate will be stored in the `cert_certificate_content` variable.
      cert_certificate_path:
        type: path
        required: false
        description:
          - The path to the certificate file to generate.
          - If *cert_certificate_to_file* is `true`, this is required.
      cert_certificate_owner:
        type: str
        required: false
        default: root
        description:
          - The owner of the certificate on Linux systems.
          - On Windows systems, this is ignored.
      cert_certificate_group:
        type: str
        required: false
        default: root
        description:
          - The group of the certificate on Linux systems.
          - On Windows systems, this is ignored.
      cert_certificate_mode:
        type: str
        required: false
        default: '0644'
        description:
          - The mode of the certificate on Linux systems.
          - On Windows systems, this is ignored.
