---
- name: Converge
  hosts:
    - subjects
  roles:
    - trippsc2.general.generate_csr
  tasks:
    - name: Copy CSR content to file
      when:
        - cert_csr_content | default('') != ''
      ansible.windows.win_copy:
        content: "{{ cert_csr_content }}"
        dest: C:\Windows\Temp\cert.csr
