---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: case1 # no existing cert
    box: jtarpley/${MOLECULE_BOX:-w2022_cis}
    memory: 2048
    cpus: 2
    groups:
      - subjects
      - windows
  - name: case2 # existing renewable cert
    box: jtarpley/${MOLECULE_BOX:-w2022_cis}
    memory: 2048
    cpus: 2
    groups:
      - subjects
      - windows
  - name: case3 # existing valid cert
    box: jtarpley/${MOLECULE_BOX:-w2022_cis}
    memory: 2048
    cpus: 2
    groups:
      - subjects
      - windows
provisioner:
  name: ansible
  inventory:
    group_vars:
      windows:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: SYSTEM
    host_vars:
      case1:
        generate_existing_private_key: false
        generate_existing_cert: false
        expected_csr: true
        expected_private_key_backup: false
      case2:
        generate_existing_private_key: true
        generate_existing_cert: true
        existing_cert_duration: +1w
        expected_csr: true
        expected_private_key_backup: true
      case3:
        generate_existing_private_key: true
        generate_existing_cert: true
        existing_cert_duration: +8w
        expected_csr: false
        expected_private_key_backup: false
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    # Removed idempotence check, because this scenario cannot be made idempotent.
    - side_effect
    - verify
    - cleanup
    - destroy
