---
- name: Verify
  hosts:
    - windows
  become: true
  tasks:
  - name: Get private key file info
    ansible.windows.win_stat:
      path: "{{ cert_private_key_path | default('C:\\Windows\\Temp\\cert.key') }}"
    register: _private_key_info

  - name: Get private key backup file info
    ansible.windows.win_stat:
      path: "{{ cert_private_key_path | default('C:\\Windows\\Temp\\cert.key') }}.bak"
    register: private_key_backup_info

  - name: Get CSR file info
    ansible.windows.win_stat:
      path: "{{ cert_csr_path | default('C:\\Windows\\Temp\\cert.csr') }}"
    register: _csr_info

  - name: Verify that private key exists
    ansible.builtin.assert:
      that:
        - _private_key_info.stat.exists
      fail_msg: Private key file does not exist.
      success_msg: Private key file exists.

  - name: Verify that private key backup exists
    when:
      - expected_private_key_backup
    ansible.builtin.assert:
      that:
        - private_key_backup_info.stat.exists
      fail_msg: Private key backup file does not exist.
      success_msg: Private key backup file exists.

  - name: Verify that private key backup does not exist
    when:
      - not expected_private_key_backup
    ansible.builtin.assert:
      that:
        - not private_key_backup_info.stat.exists
      fail_msg: Private key backup file exists.
      success_msg: Private key backup file does not exist.

  - name: Verify that CSR exists
    when:
      - expected_csr
    ansible.builtin.assert:
      that:
        - _csr_info.stat.exists
      fail_msg: CSR file does not exist.
      success_msg: CSR file exists.

  - name: Verify that CSR does not exist
    when:
      - not expected_csr
    ansible.builtin.assert:
      that:
        - not _csr_info.stat.exists
      fail_msg: CSR file exists.
      success_msg: CSR file does not exist.
