---
argument_specs:
  main:
    short_description: Generate CSR
    description:
      - This role generates a Certificate Signing Request (CSR) for a Linux or Windows machine, if an existing certificate doesn't exist or needs renewal.
      - The role should be used in conjunction with another role to sign the CSR and generate a certificate.
      - |
        This role does the following:
          - Checks if a certificate exists.
          - If the certificate does not exist or is near expiration, the role generates a private key and stores it in the `cert_private_key_content` variable.
          - Optionally, the role will save the private key to a file and backup the replaced private key.
          - If the certificate does not exist or is near expiration, the role generates a CSR and stores it at `cert_csr_content`.
          - Optionally, the role will save the CSR to a file.
    author:
      - Jim Tarpley (@trippsc2)
    options:
      cert_force_regenerate:
        type: bool
        required: false
        default: false
        description:
          - Whether to force regeneration of the CSR, even if the certificate is not near expiration.
          - If set to `true`, the role will not be idempotent.
      cert_existing_certificate_type:
        type: str
        required: false
        default: file
        choices:
          - file
          - pipe
        description:
          - The type of existing certificate to evaluate.
          - If set to `file`, the role will check the certificate file at `cert_certificate_path` making that variable required.
          - If set to `pipe`, the role will check the certificate content at `cert_existing_certificate_content`.  If that variable is not provided, the role will generate a new CSR.
      cert_certificate_path:
        type: path
        required: false
        description:
          - The path to the certificate file to generate.
          - If *cert_existing_certificate_type* is `file`, this is required.
      cert_existing_certificate_content:
        type: str
        required: false
        description:
          - The content of the existing certificate.
          - If this is provided and *cert_existing_certificate_type* is `pipe`, the certificate will be evaluated for expiration before proceeding.
          - If this is not provided and *cert_existing_certificate_type* is `pipe`, the role will generate a new CSR.
      cert_regenerate_days:
        type: int
        required: false
        default: 30
        description:
          - The number of days before the certificate expiration to regenerate the CSR.
      cert_private_key_to_file:
        type: bool
        required: false
        default: true
        description:
          - Whether to generate a private key to a file.
      cert_private_key_to_variable:
        type: bool
        required: false
        default: false
        description:
          - Whether to generate a private key to a variable.
          - If set to `true`, the role will store the private key in the `cert_private_key_content` variable.
      cert_private_key_path:
        type: path
        required: false
        description:
          - The path to the private key file to generate.
          - If *cert_private_key_to_file* is `true`, this is required.
      cert_private_key_owner:
        type: str
        required: false
        default: root
        description:
          - The owner of the private key on Linux systems.
          - On Windows systems, this is ignored.
      cert_private_key_group:
        type: str
        required: false
        default: root
        description:
          - The group of the private key on Linux systems.
          - On Windows systems, this is ignored.
      cert_private_key_mode:
        type: str
        required: false
        default: '0600'
        description:
          - The mode of the private key on Linux systems.
          - On Windows systems, this is ignored.
      cert_private_key_type:
        type: str
        required: false
        default: RSA
        choices:
          - DSA
          - ECC
          - Ed25519
          - Ed448
          - RSA
          - X25519
          - X448
        description:
          - The type of private key to generate.
      cert_private_key_size:
        type: int
        required: false
        description:
          - The size of the private key to generate.
          - If *cert_private_key_type* is `RSA` or `DSA`, this defaults to `2048`.
      cert_private_key_curve:
        type: str
        required: false
        choices:
          - secp224r1
          - secp256k1
          - secp256r1
          - secp384r1
          - secp521r1
          - secp192r1
          - brainpoolP256r1
          - brainpoolP384r1
          - brainpoolP512r1
          - sect163k1
          - sect163r2
          - sect233k1
          - sect233r1
          - sect283k1
          - sect283r1
          - sect409k1
          - sect409r1
          - sect571k1
          - sect571r1
        description:
          - The curve of the private key to generate.
          - If *cert_private_key_type* is `ECC`, this defaults to `secp384r1`.
      cert_backup_replaced_private_key:
        type: bool
        required: false
        default: true
        description:
          - Whether to backup the replaced private key.
          - If *cert_private_key_to_file* is `false`, this is ignored.
      cert_common_name:
        type: str
        required: false
        default: "{{ inventory_hostname }}"
        description:
          - The Common Name (CN) of the certificate.
      cert_subject_alternative_names:
        type: list
        required: false
        elements: str
        description:
          - The Subject Alternative Names (SANs) of the certificate.
          - DNS names should be prefixed with `DNS:`, IP addresses should be prefixed with `IP:`, and Email addresses should be prefixed with `email:`.
      cert_organization_name:
        type: str
        required: false
        description:
          - The Organization Name (O) of the certificate.
      cert_organizational_unit_name:
        type: str
        required: false
        description:
          - The Organizational Unit Name (OU) of the certificate.
      cert_locality_name:
        type: str
        required: false
        description:
          - The Locality Name (L) of the certificate.
      cert_state_or_province_name:
        type: str
        required: false
        description:
          - The State or Province Name (ST) of the certificate.
      cert_country_name:
        type: str
        required: false
        description:
          - The Country Name (C) of the certificate.
      cert_key_usage:
        type: list
        required: false
        default: 
          - digitalSignature
          - keyEncipherment
        elements: str
        choices:
          - digitalSignature
          - nonRepudiation
          - keyEncipherment
          - dataEncipherment
          - keyAgreement
          - keyCertSign
          - cRLSign
          - encipherOnly
          - decipherOnly
        description:
          - The key usage of the certificate.
      cert_key_usage_critical:
        type: bool
        required: false
        default: true
        description:
          - Whether the key usage is critical.
      cert_extended_key_usage:
        type: list
        required: false
        default: 
          - serverAuth
          - clientAuth
        elements: str
        description:
          - The extended key usage of the certificate.
      cert_extended_key_usage_critical:
        type: bool
        required: false
        default: true
        description:
          - Whether the extended key usage is critical.
      cert_basic_constraints:
        type: list
        required: false
        elements: str
        description:
          - The basic constraints of the certificate.
      cert_basic_constraints_critical:
        type: bool
        required: false
        default: true
        description:
          - Whether the basic constraints are critical.
      cert_csr_to_file:
        type: bool
        required: false
        default: false
        description:
          - Whether to generate a CSR to a file.
          - If set to `true`, the role will write the CSR to a file path specified at `cert_csr_path`.
      cert_csr_path:
        type: path
        required: false
        description:
          - The path to the CSR file to generate.
          - If *cert_csr_to_file* is `false`, this is ignored.
          - For Linux systems, this defaults to `/tmp/cert.csr`.
          - For Windows systems, this defaults to `C:\Windows\Temp\cert.csr`.
      cert_csr_owner:
        type: str
        required: false
        default: "{{ ansible_user }}"
        description:
          - The owner of the CSR on Linux systems.
          - On Windows systems, this is ignored.
      cert_csr_group:
        type: str
        required: false
        default: "{{ ansible_user }}"
        description:
          - The group of the CSR on Linux systems.
          - On Windows systems, this is ignored.
      cert_csr_mode:
        type: str
        required: false
        default: '0644'
        description:
          - The mode of the CSR on Linux systems.
          - On Windows systems, this is ignored.
