---
_cert_private_key_size: >-
  {{ cert_private_key_size if cert_private_key_type == 'RSA' or cert_private_key_type == 'DSA' else omit }}

_cert_private_key_curve: >-
  {{ cert_private_key_curve if cert_private_key_type == 'ECC' else omit }}

_cert_allowed_dsa_key_sizes:
  - 1024
  - 2048
  - 3072
  - 4096
