---
argument_specs:
  main:
    short_description: Self-Signed Certificate
    description:
      - This role generates a self-signed TLS certificate.
      - The role depends on the `trippsc2.general.generate_csr` role to generate a private key and CSR.
      - |
        The role does the following:
          - Runs the `trippsc2.general.generate_csr` role to generate a private key and CSR, if needed.
          - If the private key and CSR are generated, the role generates a self-signed certificate and stores it in the `cert_certificate_content` variable.
          - Optionally, the role will save the certificate to a file.
    author:
      - Jim Tarpley (@trippsc2)
    options:
      cert_certificate_to_file:
        type: bool
        required: false
        default: true
        description:
          - Whether to generate the certificate to a file.
          - If set to `true`, the certificate will be stored in the `cert_certificate_content` variable.
      cert_certificate_path:
        type: path
        required: false
        description:
          - The path to the certificate file to generate.
          - If *cert_certificate_to_file* is `true`, this is required.
      cert_certificate_owner:
        type: str
        required: false
        default: root
        description:
          - The owner of the certificate on Linux systems.
          - On Windows systems, this is ignored.
      cert_certificate_group:
        type: str
        required: false
        default: root
        description:
          - The group of the certificate on Linux systems.
          - On Windows systems, this is ignored.
      cert_certificate_mode:
        type: str
        required: false
        default: '0644'
        description:
          - The mode of the certificate on Linux systems.
          - On Windows systems, this is ignored.
      cert_not_after:
        type: str
        required: false
        description:
          - The date and time when the certificate will expire.
          - Refer to the **community.crypto.x509_certificate** module for the format.
          - If not provided, the certificate will expire in 3650 days.
